import Eye from './components/Eye';
import Play from './components/Play';
import Home from './components/Home';
import Plus from './components/Plus';
import Help from './components/Help';
import Minus from './components/Minus';
import Pause from './components/Pause';
import Heart from './components/Heart';
import Video from './components/Video';
import Upload from './components/Upload';
import Pencil from './components/Pencil';
import Replay from './components/Replay';
import Search from './components/Search';
import Logout from './components/Logout';
import Broken from './components/Broken';
import History from "./components/History";
import Profile from './components/Profile';
import Settings from './components/Settings';
import OpenMenu from './components/OpenMenu';
import CloseMenu from './components/CloseMenu';
import OpenFullscreen from './components/OpenFullscreen';
import CloseFullscreen from './components/CloseFullscreen';

export default function Icons({ type }: { type: string; }) {
	if (type === 'eye') return <Eye />;
	if (type === 'play') return <Play />;
	if (type === 'help') return <Help />;
	if (type === 'home') return <Home />;
	if (type === 'plus') return <Plus />;
	if (type === 'minus') return <Minus />;
	if (type === 'heart') return <Heart />;
	if (type === 'pause') return <Pause />;
	if (type === 'video') return <Video />;
	if (type === 'search') return <Search />;
	if (type === 'logout') return <Logout />;
	if (type === 'pencil') return <Pencil />;
	if (type === 'replay') return <Replay />;
	if (type === 'broken') return <Broken />;
	if (type === 'upload') return <Upload />;
	if (type === 'history') return <History />;
	if (type === 'profile') return <Profile />;
	if (type === 'settings') return <Settings />;
	if (type === 'openMenu') return <OpenMenu />;
	if (type === 'closeMenu') return <CloseMenu />;
	if (type === 'openFullscreen') return <OpenFullscreen />;
	if (type === 'closeFullscreen') return <CloseFullscreen />;

	return null;
};